---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: linting-yaml-app-
spec:
  params:
    - name: source-repo
      value: https://github.com/cloud-native-garage-method-cohort/grace-ardho-tekton-pipeline-assignment
  pipelineRef:
    name: linting-yaml-pipeline
  workspaces:
    - name: pipeline-shared-data
      volumeClaimTemplate:
        spec:
          resources:
            requests:
              storage: 1Gi
          accessModes:
            - ReadWriteOnce